/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21201 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21202 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21203 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21204 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21205 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21206 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21207 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21208 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21209 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21210 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21211 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21212 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21213 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21214 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21215 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21216 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21217 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21218 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21219 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21220 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21221 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21222 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21223 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21224 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21225 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21226 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21227 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21228 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21229 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21230 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21231 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21232 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21233 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21234 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21235 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21236 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21237 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21238 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21239 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21240 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21241 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21242 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21243 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21244 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21245 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21246 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21247 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21248 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21249 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21250 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21251 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21252 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21253 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21254 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21255 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21256 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21257 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21258 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21259 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21260 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21261 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21262 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21263 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21264 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21265 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21266 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21267 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21268 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21269 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21270 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21271 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21272 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21273 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21274 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21275 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21276 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21277 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21278 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21279 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21280 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21281 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21282 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21283 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21284 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21285 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21286 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21287 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21288 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21289 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21290 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21291 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21292 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21293 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21294 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21295 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21296 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21297 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21298 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21299 &
/home/abhishek/Documents/Work/Stat_Util/bin/rw_test_run 21300 &
